export default {
	ADD_COMMENT: 'ADD_COMMENT',
	ADD_MOVIE_FAVORITE: 'ADD_MOVIE_FAVORITE',
	GET_MOVIES: 'GET_MOVIES_ACTION',
	GET_MOVIES_PENDING: 'GET_MOVIES_PENDING',
	GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
	GET_MOVIES_STARTED: 'GET_MOVIES_STARTED',
	GET_SINGLE_MOVIE: 'GET_SINGLE_MOVIE'
};
